@startuml
scale 1500 width
title Correct Commit has Forgotten something
skinparam roundCorner 20
actor User
box "<size:20>GIT                     jalbertomr.blogspot.com</size>"
participant "Working dir" as WD #FF5555
participant "Stage" as S #99FF99
database "commit 1" as C1
database "commit 2" as C2
database "commit 3" as C3
database "commit 4" as C4
== Correct Commit has Forgotten something ==
== Make 3 commits ==
User -> WD:  create file1:v1
note right of WD #lightgray
file1:v1
end note
note left of S #Salmon
file1:v1
end note
User-> S : <color:limegreen><back:black><b> git add file1 </b></back></color>
note right of S #99FF99
file1:v1
end note
User-> C1 : <color:limegreen><back:black><b> git commit -m "file1:v1" </b></back></color>
note right of C1
HEAD
file1:v1
end note
note right of C1 #lightgray
file1:v1
end note


User -> WD:  update file1:v1->v2, create file2:v2
note right of WD #lightgray
file1:v2
end note
note left of S #Salmon
file1:v2
end note
note right of WD #lightgray
file2:v1
end note
note left of S #Salmon
file2:v1
end note

User-> C2 : <color:limegreen><back:black><b> git add file*" </b></back></color>
note right of S #99FF99
file1:v2
end note
note right of S #99FF99
file2:v1
end note

User-> C2 : <color:limegreen><back:black><b> git commit -m "file1:v2 file2:v1" </b></back></color>
note right of C2
HEAD
file1:v2 file2:v1
end note
note right of C2 #lightgray
file1:v2
end note
note right of C2 #lightgray
file2:v1
end note


User -> WD:  update file1.v2->v3
note right of WD #lightgray
file1:v3
end note
note left of S #Salmon
file1:v3
end note

User-> C3 : <color:limegreen><back:black><b> git add file*" </b></back></color>
note right of S #99FF99
file1:v3
end note

User-> C3 : <color:limegreen><back:black><b> git commit -m "file1" </b></back></color>
note right of C3
HEAD
file1:v3
end note
note right of C3 #lightgray
file1:v3
end note
note right of C3 #lightgray
file2:v1
end note

== Now wanted to return to Commit1 and add file2 in order to have a commit corrected\nmove de HEAD to Commit1, with files to WD==
== Apply command: git reset --soft HEAD~2 ==

User -> C1 : <color:limegreen><back:black><b> git reset --soft HEAD~2 </b></back></color>
note right of C1
HEAD
end note
note right of S #99FF99
file1:v3
file2:v1
end note

note right of WD #lightgray
file1:v3
file2:v1
end note
== Ready to do a new commit with files integrated as original wanted ==
User -> C4 : <color:limegreen><back:black><b> git commit -m "file1:v3 file2:v1" </b></back></color>

@enduml